#!/usr/bin/env node
/**
 * Generate the PWA icon set from the same geometry as public/favicon.svg.
 *
 * Committed PNGs would be opaque binaries in a project whose whole pitch is
 * auditability, and adding an image-processing dependency for four icons is not
 * worth it — so the PNGs are produced here with a minimal, dependency-free
 * encoder and regenerated by `npm run icons`.
 *
 * The mark is defined as analytic shapes on the same 64-unit grid the SVG uses,
 * so the vector and raster versions cannot drift: change a number here and in
 * the SVG, or neither.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { deflateSync } from 'node:zlib'

const BRAND = [0x1a, 0x56, 0xb8]
const WHITE = [0xff, 0xff, 0xff]

/** The grid the mark is drawn on. Matches the SVG viewBox. */
const UNIT = 64

/**
 * Samples per pixel per axis.
 *
 * The previous generator tested one point per pixel, which left visibly stepped
 * edges on the badge corners and the bubble — the exact thing that reads as
 * "amateur" on a home screen. Sixteen samples per pixel is plenty for shapes
 * this simple and costs milliseconds at 512.
 */
const SAMPLES = 4

/**
 * How much the mark shrinks inside a maskable icon.
 *
 * A maskable icon may be cropped to a circle of 80% of its width, so the mark
 * has to sit inside that. At 0.75 the mark's bounding box spans about 67% of
 * the icon diagonally, which clears the crop with room to spare.
 */
const MASKABLE_SCALE = 0.75

const inCircle = (x, y, cx, cy, r) => (x - cx) ** 2 + (y - cy) ** 2 <= r * r

function inRoundedRect(x, y, x0, y0, w, h, r) {
  const x1 = x0 + w
  const y1 = y0 + h
  if (x < x0 || x > x1 || y < y0 || y > y1) return false
  const nearLeft = x < x0 + r
  const nearRight = x > x1 - r
  const nearTop = y < y0 + r
  const nearBottom = y > y1 - r
  if (!((nearLeft || nearRight) && (nearTop || nearBottom))) return true
  return inCircle(x, y, nearLeft ? x0 + r : x1 - r, nearTop ? y0 + r : y1 - r, r)
}

/** Barycentric point-in-triangle. Winding-agnostic, so vertex order is free. */
function inTriangle(x, y, ax, ay, bx, by, cx, cy) {
  const d = (by - cy) * (ax - cx) + (cx - bx) * (ay - cy)
  const a = ((by - cy) * (x - cx) + (cx - bx) * (y - cy)) / d
  const b = ((cy - ay) * (x - cx) + (ax - cx) * (y - cy)) / d
  return a >= 0 && b >= 0 && a + b <= 1
}

/** The bubble and its tail — the shape Safari's pinned tab also uses alone. */
const inBubble = (x, y) =>
  inRoundedRect(x, y, 10, 13, 44, 27, 9) || inTriangle(x, y, 22, 34, 34, 34, 16.5, 52)

/** Two peers and the channel between them, knocked back out of the bubble. */
const inLink = (x, y) =>
  inRoundedRect(x, y, 23, 25.1, 18, 2.8, 1.4) ||
  inCircle(x, y, 23, 26.5, 3.5) ||
  inCircle(x, y, 41, 26.5, 3.5)

/**
 * How the badge meets the edge of the file.
 *
 *   rounded   the badge rounds its own corners and the rest is transparent —
 *             right for a favicon and for PWA icons of purpose "any"
 *   bleed     colour to every edge, mark at full size — required for
 *             apple-touch-icon, because iOS applies its own rounded mask and a
 *             pre-rounded icon shows black in the corners
 *   maskable  colour to every edge, mark shrunk into the safe zone, for
 *             launchers that crop to an arbitrary shape
 */
function colourAt(x, y, shape) {
  if (shape === 'rounded' && !inRoundedRect(x, y, 0, 0, UNIT, UNIT, 14)) return null

  // Scale the mark about the centre of the grid for maskable icons.
  const scale = shape === 'maskable' ? MASKABLE_SCALE : 1
  const mx = (x - UNIT / 2) / scale + UNIT / 2
  const my = (y - UNIT / 2) / scale + UNIT / 2

  if (inBubble(mx, my)) return inLink(mx, my) ? BRAND : WHITE
  return BRAND
}

/** Render to RGBA, averaging SAMPLES x SAMPLES points per pixel for smooth edges. */
function render(size, shape) {
  const pixels = new Uint8Array(size * size * 4)
  const perSample = UNIT / size / SAMPLES
  const total = SAMPLES * SAMPLES

  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let r = 0
      let g = 0
      let b = 0
      let covered = 0

      for (let sy = 0; sy < SAMPLES; sy++) {
        for (let sx = 0; sx < SAMPLES; sx++) {
          const x = (px * UNIT) / size + (sx + 0.5) * perSample
          const y = (py * UNIT) / size + (sy + 0.5) * perSample
          const colour = colourAt(x, y, shape)
          if (!colour) continue
          r += colour[0]
          g += colour[1]
          b += colour[2]
          covered++
        }
      }

      const offset = (py * size + px) * 4
      if (covered === 0) continue
      // Average only the covered samples, so a partly-covered edge pixel keeps
      // the mark's colour at reduced alpha rather than being pulled to black.
      pixels[offset] = Math.round(r / covered)
      pixels[offset + 1] = Math.round(g / covered)
      pixels[offset + 2] = Math.round(b / covered)
      pixels[offset + 3] = Math.round((covered / total) * 255)
    }
  }
  return pixels
}

/** Minimal PNG encoder: filter type 0 per scanline, one IDAT, no ancillary chunks. */
function encodePng(pixels, size) {
  const raw = Buffer.alloc(size * (size * 4 + 1))
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0
    Buffer.from(pixels.buffer, y * size * 4, size * 4).copy(raw, y * (size * 4 + 1) + 1)
  }

  const chunk = (type, data) => {
    const length = Buffer.alloc(4)
    length.writeUInt32BE(data.length)
    const body = Buffer.concat([Buffer.from(type, 'ascii'), data])
    const crc = Buffer.alloc(4)
    crc.writeUInt32BE(crc32(body) >>> 0)
    return Buffer.concat([length, body, crc])
  }

  const ihdr = Buffer.alloc(13)
  ihdr.writeUInt32BE(size, 0)
  ihdr.writeUInt32BE(size, 4)
  ihdr[8] = 8 // bit depth
  ihdr[9] = 6 // colour type: RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[n] = c
  }
  return table
})()

function crc32(buffer) {
  let crc = -1
  for (const byte of buffer) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8)
  return crc ^ -1
}

mkdirSync(new URL('../public/icons/', import.meta.url), { recursive: true })

for (const [name, size, shape] of [
  // 32 is the classic favicon fallback for browsers that ignore the SVG one.
  ['icon-32.png', 32, 'rounded'],
  ['icon-192.png', 192, 'rounded'],
  ['icon-512.png', 512, 'rounded'],
  ['icon-maskable-512.png', 512, 'maskable'],
  ['apple-touch-icon.png', 180, 'bleed'],
]) {
  const path = new URL(`../public/icons/${name}`, import.meta.url)
  writeFileSync(path, encodePng(render(size, shape), size))
  console.log(`wrote public/icons/${name} (${size}x${size}, ${shape})`)
}
